### ISSUE TITLE
Obfuscated ores showing when a builder excavates down to stone before building something

### ISSUE THREAD

**Issue by axemwa** [mcmonkey4eva/Builder#3]
Obfuscated ores(the ones that show when players attempt to use an xray mod when anti-xray is switched on in paper.yml) are showing when the builder digs down to a cetain level when attmepting to build something, it's nothing major but just something I thought I'd point out and to ask if there's a way around it without having to remove the anti-xray feature. Also the obfuscated ores do dissapear when a player attempts to mine or hit them. EDIT - The obfuscated ores also seem to be acting as a light source.

![image](https://user-images.githubusercontent.com/37608633/42120287-2e3a7748-7c58-11e8-8aac-a17df113475b.png)

**Comment by mcmonkey4eva** [comment]
That sounds like an issue with the obfuscator plugin/setup you have, not builder...

**Comment by axemwa** [comment]
Thanx yeah I realized that was what's causing it just seeing if u know a way to get past it/stop it from happening for npcs, these are the settings in paper.yml, would I have to disable and use a seperate anti-xray plugin thats compatible with builder or is there another way such as changing engine mode or something in paper.yml anti-xray section?

anti-xray:
      enabled: true
      engine-mode: 2
      chunk-edge-mode: 1
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - ender_chest
      replacement-blocks:
      - stone
      - planks

**Comment by mcmonkey4eva** [comment]
You'd... have to ask paper developers about that?
I don't use paper myself and don't really know anything about configuring it.

**Comment by axemwa** [comment]
Ok :) thanx anyway

**Comment by axemwa** [comment]
@mcmonkey4eva I was also wondering how do you get more than one builder to work on the same building can't seem to work that part out.

**Comment by mcmonkey4eva** [comment]
I'll be honest, I don't know.
Builder was started by aufdemrand, but didn't get anywhere til jrbudda took over... both of those people have long since disappeared from Minecraft, and builder was updated through a few versions by Morphan1, who is still contactable (though not actively developing Minecraft stuff anymore) but never really used or cared about Builder other than updating it to latest minecraft versions, but since he stopped working on things here I updated it to 1.12 myself and that's basically where we are now. I've never used it or cared about it beyond keeping it bare minimum functional.

I would love for a Java developer in the Citizens community to step up and properly clean + actively work on Builder. If any such developer becomes interested, we (Citizens team) will happily provide them with assistance, knowledge, build server, etc. as needed.
For the moment right now, we don't have any such person available.
